spring.application.name=patient-services

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.url=jdbc:h2:mem:testdb
#
#spring.datasource.username=sa
#spring.datasource.password=
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=ALWAYS

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=4000

logging.level.root=info